"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IPC_CHANNELS = void 0;
exports.IPC_CHANNELS = {
    workspaceGetSnapshot: "workspace:getSnapshot",
    workspaceAddProject: "workspace:addProject",
    workspaceAddWorktree: "workspace:addWorktree",
    workspaceSetActive: "workspace:setActive",
    workspaceCreateThread: "workspace:createThread",
    workspaceReorderThreads: "workspace:reorderThreads",
    workspaceSetActiveThread: "workspace:setActiveThread",
    workspaceDeleteThread: "workspace:deleteThread",
    workspaceRenameThread: "workspace:renameThread",
    workspaceDidChange: "workspace:didChange",
    /** Repo working tree may have changed (save, patch, etc.); refresh diff / git state in renderer. */
    workingTreeFilesDidChange: "diff:workingTreeFilesDidChange",
    runStart: "run:start",
    runSendInput: "run:sendInput",
    runInterrupt: "run:interrupt",
    diffChangedFiles: "diff:changedFiles",
    diffRepoStatus: "diff:repoStatus",
    diffFileDiff: "diff:fileDiff",
    diffWorkingTree: "diff:workingTree",
    diffStageAll: "diff:stageAll",
    diffUnstageAll: "diff:unstageAll",
    diffDiscardAll: "diff:discardAll",
    diffStagePaths: "diff:stagePaths",
    diffUnstagePaths: "diff:unstagePaths",
    diffDiscardPaths: "diff:discardPaths",
    diffGitFetch: "diff:gitFetch",
    diffGitPush: "diff:gitPush",
    diffGitCommit: "diff:gitCommit",
    diffIsGitRepository: "diff:isGitRepository",
    diffInitGitRepository: "diff:initGitRepository",
    filesList: "files:list",
    filesSearch: "files:search",
    filesRead: "files:read",
    filesWrite: "files:write",
    filesCreate: "files:create",
    filesDelete: "files:delete",
    editApplyPatch: "edit:applyPatch",
    previewSetUrl: "preview:setUrl",
    previewProbeUrl: "preview:probeUrl",
    terminalPtyCreate: "terminal:ptyCreate",
    terminalPtyWrite: "terminal:ptyWrite",
    terminalPtyResize: "terminal:ptyResize",
    terminalPtyKill: "terminal:ptyKill",
    terminalPtyListSessions: "terminal:ptyListSessions",
    terminalPtyGetBuffer: "terminal:ptyGetBuffer",
    terminalPtyData: "terminal:ptyData",
    dialogPickRepoDirectory: "dialog:pickRepoDirectory",
    workspaceCreateWorktreeGroup: "workspace:createWorktreeGroup",
    workspaceDeleteWorktreeGroup: "workspace:deleteWorktreeGroup",
    workspaceListBranches: "workspace:listBranches",
    workspaceWorktreeHealth: "workspace:worktreeHealth",
    workspaceSyncWorktrees: "workspace:syncWorktrees",
    /** macOS often captures ⌘, for the app menu; main sends this so the renderer can open settings. */
    uiOpenWorkspaceSettings: "ui:openWorkspaceSettings"
};
